package org.example.project.utils

const val EXPENSE_SCREEN_LOADING_TEST_TAG = "EXPENSE_SCREEN_LOADING_TEST_TAG"
const val EXPENSE_SCREEN_ERROR_TEST_TAG = "EXPENSE_SCREEN_ERROR_TEST_TAG"
const val EXPENSE_SCREEN_CONTENT_TEST_TAG = "EXPENSE_SCREEN_CONTENT_TEST_TAG"
const val EXPENSE_SCREEN_SUCCESS_TEST_TAG = "EXPENSE_SCREEN_SUCCESS_TEST_TAG"
const val EXPENSE_EMPTY_SUCCESS_TEST_TAG = "EXPENSE_EMPTY_SUCCESS_TEST_TAG"
const val EXPENSE_SCREEN_SUCCESS_TOTAL_TEST_TAG = "EXPENSE_SCREEN_SUCCESS_TOTAL_TEST_TAG"
const val EXPENSE_SCREEN_CLICK_ITEM_TEST_TAG = "EXPENSE_SCREEN_CLICK_ITEM_TEST_TAG"
const val EXPENSE_DETAIL_TEST_TAG = "EXPENSE_DETAIL_TEST_TAG"